### ISSUE TITLE
It seems the GTS2 Mini can display scales for some parameters

### ISSUE THREAD

**Issue by JulienMaille** [Tnxec2/py_amazfit_tools#12]
![0000](https://user-images.githubusercontent.com/182520/135670731-5dd9700b-6463-48b3-a85a-620f494734ae.png)
[9dd4668a2762a86e8b837b933a23efe4.zip](https://github.com/Tnxec2/py_amazfit_tools/files/7269443/9dd4668a2762a86e8b837b933a23efe4.zip)

It is a bit weird, on this watchface the blue circle is obtained with a set of images.
But the green circle (for steps) seems to be drawn by the watch
```
Parsing descriptor for parameter 7...
4 (22): 28 bytes
    1 ( 8): 239 EF    # x coord.
    2 (10): 84 54     # y coord.
    3 (18): 33 21     # width?
    4 (20): 33 21     # height?
    5 (28): 180 B4    # start angle
    6 (30): 540 21C   # stop angle
    7 (38): 8  8      # ????
    8 (40): 18446744073694918516 FFFFFFFFFF 20B774  # green color
```

**Comment by JulienMaille** [comment]
And the orange circle (for calories)
```
Parsing descriptor for parameter 15...
4 (22): 28 bytes
    1 ( 8): 239 EF
    2 (10): 84 54
    3 (18): 17 11
    4 (20): 17 11
    5 (28): 180 B4
    6 (30): 540 21C
    7 (38): 10  A
    8 (40): 18446744073708659470 FFFFFFFFFFF2630E
```

**Comment by JulienMaille** [comment]
Would be nice to list hidden features that are not available in the official editor

**Comment by Tnxec2** [comment]
i have added preview for circlescale

**Comment by Tnxec2** [comment]
we can list all additional features in Readme
