### ISSUE TITLE
Role of Unknown7 in Number

### ISSUE THREAD

**Issue by JulienMaille** [Tnxec2/py_amazfit_tools#13]
I did a quick try and repacked a watchface with a positive value for Unknown7 (Minutes).
Looks like it's meant to offset the digits vertically.
![image](https://user-images.githubusercontent.com/182520/135709504-0a6133c9-7afb-40ae-ae13-e2b2862bd9ae.png)
```json
{
  "Info": {
    "DeviceId": 73
  },
  "Background": {
    "Image": {
      "X": 133,
      "Y": 100,
      "ImageIndex": 0
    },
    "Preview": {
      "X": 0,
      "Y": 0,
      "ImageIndex": 1
    },
    "PreviewKorean": {
      "X": 0,
      "Y": 0,
      "ImageIndex": 1
    },
    "PreviewChinese": {
      "X": 0,
      "Y": 0,
      "ImageIndex": 1
    }
  },
  "DateBlock": {
    "Date": {
      "PaddingZeroMonth": true,
      "PaddingZeroDay": true,
      "Unknown6": 0
    }
  },
  "TimeDigital": {
    "Hours": {
      "TopLeftX": 42,
      "TopLeftY": 100,
      "BottomRightX": 147,
      "BottomRightY": 177,
      "Alignment": "TopLeft",
      "Spacing": 0,
      "Unknown7": 0,
      "ImageIndex": 2,
      "ImagesCount": 10
    },
    "PaddingZeroHours": true,
    "HoursFollowPosition": false,
    "Time": {
      "Unknown1": 1,
      "Minutes": {
        "TopLeftX": 167,
        "TopLeftY": 100,
        "BottomRightX": 272,
        "BottomRightY": 177,
        "Alignment": "TopLeft",
        "Spacing": 0,
        "Unknown7": 50,
        "ImageIndex": 2,
        "ImagesCount": 10
      },
      "PaddingZeroMinutes": true,
      "PaddingZeroSeconds": true,
      "MinutesFollowHours": false,
      "SecondsFollowMinutes": false
    }
  }
}
```

**Comment by JulienMaille** [comment]
negative values will offset upward

**Comment by SashaCX75** [comment]
I would also check if there is a maximum limit. For example, the "Spacing" parameter in GTR 2 can only be changed from -128 to 127.

**Comment by JulienMaille** [comment]
> I would also check if there is a maximum limit. For example, the "Spacing" parameter in GTR 2 can only be changed from -128 to 127.

Does this vertical offset parameter exists for the GTS or Bip?

**Comment by SashaCX75** [comment]
На GTS для времени вообще другой принцип задания положения. На GTS 2 известно только о горизонтальном смещении  "Spacing".

As I understand it, the vertical offset can be set not only for the time, but also for the date and for activities?

**Comment by JulienMaille** [comment]
Yes, this offset is present in date and activities

**Comment by Tnxec2** [comment]
I think with this vertical offset and negative spacing it is possible draw numbers vertical. @JulienMaille can you check this on watch

**Comment by JulienMaille** [comment]
> I think with this vertical offset and negative spacing it is possible draw numbers vertical. @JulienMaille can you check this on watch

Hehe I had the same idea. But you know that original zepp watchfaces achieve vertical numbers by using the Independent Digit adress

**Comment by JulienMaille** [comment]
@Tnxec2 wanna change Unknown7 to a better name and move on?

**Comment by Tnxec2** [comment]
it is now: "VerticalOffset"
