### ISSUE TITLE
Special custom watchface from Zepp application

### ISSUE THREAD

**Issue by JulienMaille** [Tnxec2/py_amazfit_tools#18]
Here is a funny thing to tinker,
In Zepp application you can select a background, a text color and it will generate a watchface for you.
The resulting watchface is really weird.
- header is shorter and different
- it seems there's a first section that describe the template watchface, ie. zepp demo background and white text
- then further in the bin file you have the real generated watchface, but I believe the colored digits are drawn by the watch, they are not pre-rendered images

This was reported to me by Lazim, props to him
It looks like this
![image](https://user-images.githubusercontent.com/182520/136089802-054dec5c-5f47-42dd-8e57-774a8586b377.png)

and the bin:
[ret.zip](https://github.com/Tnxec2/py_amazfit_tools/files/7288707/ret.zip)

**Comment by Tnxec2** [comment]
such wf have GTS2 and GTR2 too. I don't know how to unpack this.

**Comment by JulienMaille** [comment]
So you think this .bin file is universal and would work on other watches?
