### ISSUE TITLE
Unknown PulseProgressElement

### ISSUE THREAD

**Issue by JulienMaille** [Tnxec2/py_amazfit_tools#22]
it seems wf creation handles parameters up to id 6
https://github.com/Tnxec2/py_amazfit_tools/blob/da2566870a76f8f2f535c03672abdafa80e7d9e2/watchFaceParser/models/gts2mini/elements/activity/pulseProgressElement.py#L43-L50

while parsing has id 7 and 8
https://github.com/Tnxec2/py_amazfit_tools/blob/da2566870a76f8f2f535c03672abdafa80e7d9e2/watchFaceParser/elements/gts2mini/progress.py#L14-L16

**Comment by Tnxec2** [comment]
yes, in preview generator i don't need NoDataImage and i don't known what UnknownImage mean, so i don't process this.
