### ISSUE TITLE
Some bugs into GTS2Mini

### ISSUE THREAD

**Issue by T-Troll** [Tnxec2/py_amazfit_tools#31]
I play with pack/unpack, it works in general, but have 2 bugs i found:

1. "Weather" shortcut switch to Music, in fact - seems like wrong ID.
2. At GTS2Mini, Weather shotrcut defined not in "Shortcuts", but into "VUIndex" of the "Weather" block. But if i try to add it, i got "Unknown humidity type" error at packing and weather block stop working on device.

PS: I can provide watch face .bin which utilize both shortcuts to check.

**Comment by JulienMaille** [comment]
I can look at this. Are those shortcuts available in official zepp editor?

**Comment by T-Troll** [comment]
I need to apologize - i just use older version packed to .exe. Latest one work correctly, so i close this issue.
