### ISSUE TITLE
So many MonthAndDay variants

### ISSUE THREAD

**Issue by JulienMaille** [Tnxec2/py_amazfit_tools#5]
We already have `OneLineMonthAndDay` and `MonthAndDay` but this watchface seems to have another parameter address for month and day. Does it look like anything that already exists in Bip/GTS2 watchfaces?
![0000](https://user-images.githubusercontent.com/182520/135091486-053db693-bf1e-4bb0-abd7-22f654cdb77d.png)
[6608e628967af66d1b74f8f9952596d7.zip](https://github.com/Tnxec2/py_amazfit_tools/files/7244144/6608e628967af66d1b74f8f9952596d7.zip)

**Comment by Tnxec2** [comment]
can i have a bin for this

**Comment by Tnxec2** [comment]
it may be that the developers have taken over some parts of old structure. and have added new features

**Comment by JulienMaille** [comment]
I added the bin file

**Comment by Tnxec2** [comment]
this look like a array of numbers
` 5 Value: None
 5.1 Value: None
 5.1.1 Value: None
 5.1.1.1 Value: None
 5.1.1.1.1 Value: 154
 5.1.1.1.2 Value: 45
 5.1.1.1.3 Value: 214
 5.1.1.1.4 Value: 91
 5.1.1.1.5 Value: 18
 5.1.1.1.6 Value: 0
 5.1.1.1.7 Value: 0
 5.1.1.1.8 Value: 22
 5.1.1.1.9 Value: 10
 5.1.1.4 Value: None
 5.1.1.4.1 Value: 229
 5.1.1.4.2 Value: 45
 5.1.1.4.3 Value: 289
 5.1.1.4.4 Value: 91
 5.1.1.4.5 Value: 18
 5.1.1.4.6 Value: 0
 5.1.1.4.7 Value: 0
 5.1.1.4.8 Value: 22
 5.1.1.4.9 Value: 10`

**Comment by Tnxec2** [comment]
yes, this is completely different code for day and month

**Comment by Tnxec2** [comment]
i have no idea why

**Comment by JulienMaille** [comment]
Maybe some official Zepp watchface have been designed with an old revision of the tool. Do you see anything different in the header?

**Comment by Tnxec2** [comment]
I don't see anything suspicious

**Comment by SashaCX75** [comment]
I think for the correct unpacking of this bin file, you need to change the Date class
```
class Date:
    definitions = {
        1: { 'Name': 'MonthAndDayLittle', 'Type': MonthAndDayLittle},
        2: { 'Name': 'OneLineMonthAndDay', 'Type': OneLineMonthAndDay},
        4: { 'Name': 'PaddingZeroMonth', 'Type': 'bool'},
        5: { 'Name': 'PaddingZeroDay', 'Type': 'bool'},
        6: { 'Name': 'Unknown6', 'Type': 'long'},
        9: { 'Name': 'MonthAndDay', 'Type': MonthAndDay},
    }
```
And add a new class accordingly. The name of the class is chosen arbitrarily, perhaps a different name would be better.
```
class MonthAndDayLittle:
    definitions = {
        1: {'Name': 'Month', 'Type': Number},
        4: {'Name': 'Day', 'Type': Number},
    }
```

**Comment by JulienMaille** [comment]
Maybe this one is MonthAndDay while `9: { 'Name': 'MonthAndDay'` should be YearMonthAndDay?

**Comment by SashaCX75** [comment]
Perhaps. It's hard to tell from a single dial. After all, the new class should also have parameters with id 2 and id 3.

**Comment by Tnxec2** [comment]
@JulienMaille, can you look other faces from Zepp with similar date block. Or is it one only?

**Comment by Tnxec2** [comment]
i make this as "MonthAndDayAlt" - it mean alternate
